/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/books": {
    /** 登録されているすべての本を取得する */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["outputs.BookResponse"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** 1件または複数件の本をまとめて登録します */
    post: {
      parameters: {
        body: {
          /** 登録する本のリスト */
          books: definitions["inputs.Book"][];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["outputs.BookResponse"][];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
}

export interface definitions {
  "inputs.Book": {
    author?: string;
    author_kana?: string;
    description?: string;
    isbn?: string;
    title?: string;
    title_kana?: string;
  };
  "outputs.BookResponse": {
    author?: string;
    author_kana?: string;
    description?: string;
    id?: number;
    isbn?: string;
    title?: string;
    title_kana?: string;
  };
}

export interface operations {}

export interface external {}
