/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/books": {
    /** 登録されているすべての本を取得する */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["outputs.BookResponse"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** 1件または複数件の本をまとめて登録します */
    post: {
      parameters: {
        body: {
          /** 登録する本のリスト */
          books: definitions["inputs.Book"][];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["outputs.BookResponse"][];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/tags": {
    /** タグ一覧を取得する */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["outputs.TagResponse"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
}

export interface definitions {
  "inputs.Book": {
    author: string;
    author_kana?: string;
    description?: string;
    isbn?: string;
    state?: definitions["inputs.BookStatus"];
    title: string;
    title_kana?: string;
  };
  /** @enum {string} */
  "inputs.BookStatus": "default" | "damaged" | "lending" | "lost";
  "outputs.BookResponse": {
    author?: string;
    author_kana?: string;
    created_at?: string;
    description?: string;
    id?: number;
    isbn?: string;
    /** @description Tags        []int  `json:"tags"` */
    tags?: number[];
    state?: definitions["outputs.BookStatus"];
    title?: string;
    title_kana?: string;
  };
  /** @enum {string} */
  "outputs.BookStatus": "default" | "damaged" | "lending" | "lost";
  "outputs.TagResponse": {
    id: number;
    name: string;
  };
}

export interface operations {}

export interface external {}
